/* Generated by Yosys 0.55 (git sha1 60f126cd00c94892782470192d6c9f7abebe7c05, clang++ 17.0.0 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "relu.sv:2.1-13.10" *)
module relu(data_in, data_out);
  (* src = "relu.sv:5.42-5.49" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "relu.sv:6.35-6.43" *)
  output [7:0] data_out;
  wire [7:0] data_out;
  assign data_out[0] = data_in[7] ? (* src = "relu.sv:11.23-11.59" *) 1'h0 : data_in[0];
  assign data_out[1] = data_in[7] ? (* src = "relu.sv:11.23-11.59" *) 1'h0 : data_in[1];
  assign data_out[2] = data_in[7] ? (* src = "relu.sv:11.23-11.59" *) 1'h0 : data_in[2];
  assign data_out[3] = data_in[7] ? (* src = "relu.sv:11.23-11.59" *) 1'h0 : data_in[3];
  assign data_out[4] = data_in[7] ? (* src = "relu.sv:11.23-11.59" *) 1'h0 : data_in[4];
  assign data_out[5] = data_in[7] ? (* src = "relu.sv:11.23-11.59" *) 1'h0 : data_in[5];
  assign data_out[6] = data_in[7] ? (* src = "relu.sv:11.23-11.59" *) 1'h0 : data_in[6];
  assign data_out[7] = 1'h0;
endmodule
